### ISSUE TITLE
QG 4 & 5 final preperation

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#218]
**As** PO,
**I want** to pass all QG's,
**so that** we are allowed to release in the 3.2 Release

## Hints / Details

Board for Tracking:
- https://github.com/orgs/eclipse-tractusx/projects/26/views/9?filterQuery=status%3AInbox+is%3Aopen+label%3A+irs+-issue-type%3Afeature

## Outcome / Acceptance Criteria
- [x] Release Documentation - Source Code
   - [x] All active and relevant Release Guidelines TRG are fulfilled (with confirmation by DevSecOps SystemTeam). https://github.com/eclipse-tractusx/sig-release/issues/85
   - [x] All TRG are checked and aligned with https://eclipse-tractusx.github.io/docs/release
- [x] Release Documentation - * Documents is up to date and completed for relevant product version.
  - [x] Architecture Documents https://github.com/eclipse-tractusx/sig-release/issues/85 >> Do 16.11.2023
  - [x]  Administrator`s Guide (User assistance) https://github.com/eclipse-tractusx/sig-release/issues/85 >> Do 16.11.2023
  - [x]  End-User Manual (User assistance) https://github.com/eclipse-tractusx/sig-release/issues/85 >> Do 16.11.2023
  - [x]  Interfaces Documentation https://github.com/eclipse-tractusx/sig-release/issues/85 >> Do 16.11.2023
 - [x]  IRS Release 23.12 - Security Acceptance Criteria 
   - [x]  Static Application Security Testing (SAST) https://github.com/eclipse-tractusx/sig-release/issues/86
   - [x] Install the release on PEN environment, see https://confluence.catena-x.net/pages/viewpage.action?pageId=40503341
   - [x]  Dynamic Application Security Testing (DAST) https://github.com/eclipse-tractusx/sig-release/issues/86
   - [x]  Secret scanning https://github.com/eclipse-tractusx/sig-release/issues/86
   - [x]  Software Composition Analysis (SCA) https://github.com/eclipse-tractusx/sig-release/issues/86
   - [x]  Container Scan conducted https://github.com/eclipse-tractusx/sig-release/issues/86
   - [x]  Infrastructure as Code IaC code must be scanned. https://github.com/eclipse-tractusx/sig-release/issues/86

### Outcome
- ...

### Acceptance Criteria
- [x] QG are prepared

## Out of Scope

- ...

**Comment by jzbmw** [comment]
- [ ] Test if that works

**Comment by mkanal** [comment]
Hey @ds-jhartmann 
I will assign the ticket to you to arrange first TRG alignments with @almadigabor. As we check the TRGs in the github action there might not be a gap between release version and the current TRGs? 
Thank you very much
Martin

**Comment by mkanal** [comment]
PO Acceptance by @jzbmw in Daily .
