### ISSUE TITLE
Wrong http status when Job is running and parameter returnUncompletedJob set to true

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/item-relationship-service#279]
## Description
According to documentation and swagger contract we should return 206 http status, but currently we are returning 200 when job is still running.

## Tasks 
- [x] Add INT or E2E tests covering 206 return code for incomplete results <html>Return job with current processed item graph for the requested id. 

## Current behavior
200 http status is being returned

## Expected behavior
Return 206 HTTP status

![Image](https://github.com/eclipse-tractusx/item-relationship-service/assets/100765908/adaf3547-9097-45aa-aa1d-016d2bf71edf)

## Outcome 
- [x] No issues could be found during QA-review. 
- [x] IRS-job requests are responded with http code 206 as long as the desired job is in status _RUNNING_, independent of _returnUncompletedJob_ settings. 
- [x] Tavern tests are adjusted and one more created, please see [PR #649](https://github.com/catenax-ng/tx-item-relationship-service/pull/649).
- [x] Follow up ticket for adjusting the http code 206 for all other job responses has been created as discussed: #289.
Ticket is ready for PO-review.

**Comment by mkanal** [comment]
PO acceptance of behalf of @jzbmw all AC is done.
