### ISSUE TITLE
Umbrella Helm research

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#375]
**As** PO ,
**I want** to support the umbrella initiative ,
**so that** we can show what is possible with TX .

## Link 
- blocks #226 

## Hints / Details

- Check all solutions 
- MXD
- IRS Localhost deployment
- Umbrella Helm Chart from 23.12. 
- Trace-X Data Provider
- Check https://github.com/eclipse-tractusx/sig-release/ repos for more information 

### Outcome
- ...
### Acceptance Criteria
- [ ] Get in contact @evegufy to align on their initial research 
- [ ] to have a good overview of the current solutions - check the solutions of other teams (please refer to (#hint) section)
- [ ] irs helm seeding data of policies with only helm functionalities
- [ ] have a strategic dev meeting how to handle the e2e initiative (Ask @jzbmw for participants to invite, invite @mkanal as well)
- [ ] Outcome of the research, is documented in a sufficient way in the concept folder structure of the repository https://github.com/eclipse-tractusx/item-relationship-service/tree/main/docs/concept

## Out of Scope

- ...

**Comment by jzbmw** [comment]
further usefull source of info the matrix chat: https://chat.eclipse.org/#/room/#tractusx-umbrella-chart:matrix.eclipse.org

**Comment by ds-jhartmann** [comment]
Planning 2: 
- for seeding of data, take a look at Helm Chart Hooks. This might be suitable

**Comment by jzbmw** [comment]
Please get in contact with @jzbmw

**Comment by jzbmw** [comment]
Helm Chart for a Data Provider : EDC, SubmodelServer, Registry

**Comment by ds-jhartmann** [comment]
Created a Data Provider Helm Chart to be used in e2e-testing Umbrella Chart: https://github.com/catenax-ng/tx-item-relationship-service/pull/788
After review, the Data Provider as well as the Submodelserver Chart will be contributed to https://github.com/eclipse-tractusx/e2e-testing

**Comment by ds-jhartmann** [comment]
Created contribution in E2E-testing repository https://github.com/eclipse-tractusx/e2e-testing/pull/53

**Comment by ds-jhartmann** [comment]
- [x] Get in contact evegufy to align on their initial research 
- [x] to have a good overview of the current solutions - check the solutions of other teams (please refer to (#hint) section)
- [x] irs helm seeding data of policies with only helm functionalities
- [x] have a strategic dev meeting how to handle the e2e initiative (Ask @jzbmw for participants to invite, invite @mkanal as well)
- [ ] ~Outcome of the research, is documented in a sufficient way in the concept folder structure of the repository https://github.com/eclipse-tractusx/item-relationship-service/tree/main/docs/concept~ did not create a concept, since I already created the testdata seeding helm hook
- [x] Helm Chart for a Data Provider : EDC, SubmodelServer, Registry
