### ISSUE TITLE
Umbrella Helm Support

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#469]
**As** team
**I want** supporting activities 
**so that** we are able to flexible contributing the umbrella HELM Chart 

## Hints / Details

- ...

## Acceptance Criteria

- [x] Participating in meeting 
- [x] Research 
- [x] Active communication in teams channel 
- [x] Alignments with companies responsibles 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
Prepared PR with MIW and Vault https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/57 
Chart install workflow is failing right now, so this still needs to be fixed

**Comment by ds-jhartmann** [comment]
Prepared PR for Dataprovider Chart https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/53

**Comment by ds-jhartmann** [comment]
Efforts will be continued in https://github.com/eclipse-tractusx/item-relationship-service/issues/490

**Comment by mkanal** [comment]
WFM. 
@jzbmw  Kindly ask for PO review.
