### ISSUE TITLE
Umbrella Helm Support - Part II

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/item-relationship-service#490]
**As** team
**I want** supporting activities 
**so that** we are able to flexible contributing the umbrella HELM Chart 

## Hints / Details
- ...

## Acceptance Criteria
- [x] Participating in meeting 
- [x] Research 
- [x] Active communication in teams channel 
- [x] Alignments with companies responsibles 

## Out of Scope
- ...

**Comment by mkanal** [comment]
Umbrella HELM Support was done for the current Iteration.
